spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  datasource:
    url: jdbc:h2:mem:demo?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: demo
    password:
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl.auto: create-drop
        default_schema: public
        format_sql: true
  jackson.serialization.write-dates-as-timestamps: false
logging:
  level:
    org.hibernate:
      SQL: error #debug
      type.descriptor.sql.BasicBinder: error #trace
